
spring:
  datasource:
    url: "데이터베이스 스키마"
    username: root
    password: "비밀번호"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "client-id"
            client-secret: "secret-key"
            scope:
              - email
              - profile
          kakao:
            client-id: "client-id"
            client-secret: "secret-key"
            scope:
              - account_email
              - profile_nickname
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-name: kakao
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
logging:
  level:
    org.springframework : info
#    org.springframework.security: debug
jwt:
  issuer: "발행자"
  secret_key: "비밀번호"
